name: Tests

on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compilation du projet
        run: |
          mkdir build
          cd build
          cmake ..
          make

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test fonction add
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test fonction sub
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator sub 10 5

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test fonction mul
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator mul 10 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test fonction div
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator div 10 5

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test fonction div
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator car 5

  Deployment:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"